clear
clc
figure(1)
plot(RDM(:,5))
%% Sets of three inputs (no figure given)


%MATTHEW

fh=figure('units','normalized','position',[0 0.3 1 .5]);

linecolors={'r' [0 .5 0] 'b' 'k'};
h3i=plotNy(WL_GA_M(:,1),WL_GA_M(:,4),1,...
    PREC_RDM(:,1),PREC_RDM(:,3)*25.4,2,...
    RDM(:,1),RDM(:,3),3,...
    FC(:,1),FC(:,2),4,...
    'Linewidth',2,...
    'YAxisLabels',{'[m]' '[mm]' '[m^3/s]','[SV]'},...
    'LineColor',linecolors,...
    'FontSize',22,...
    'Ylim',[-0.2 2.5; 0 7*25.4; 140 280; 15 40],...
    'Fontname','TimesNewRoman',...
    'Parent',fh,... 
    'Grid','on',...
    'LegendString',{'Water level anomailes' 'Precipitation' 'River discharge' 'Florida current'});
set(gca,'XLim',[min(RDM(:,1)) max(RDM(:,1))],'XTick',[min(RDM(:,1)):(max(RDM(:,1))-min(RDM(:,1)))/11:max(RDM(:,1))])
datetick('x','mmmdd','keepticks')
% xtickangle(45)
set(gcf,'color','w');


%Change the axis colors to match the requested line colors
for i=1:length(h3i.ax)
	set(h3i.ax(i),'ycolor',linecolors{i});	
end


saveas(fh,sprintf('/Users/kpark350/Ga_tech/Paper/DCF/OSM/Comp_GA_M.png'));


% DORIAN
fh=figure('units','normalized','position',[0 0.3 1 .5]);

linecolors={'r' [0 .5 0] 'b' 'k'};
h3i=plotNy(WL_GA_D(:,1),WL_GA_D(:,4),1,...
    PREC_RDD(:,1),PREC_RDD(:,3)*25.4,2,...
    RDD(:,1),RDD(:,3),3,...
    FC(:,1),FC(:,2),4,...
    'Linewidth',2,...
    'YAxisLabels',{'[m]' '[mm]' '[m^3/s]','[SV]'},...
    'LineColor',linecolors,...
    'FontSize',22,...
    'Ylim',[-0.2 2.5; 0 7*25.4; 140 280; 15 40],...
    'Fontname','TimesNewRoman',...
    'Parent',fh,... 
    'Grid','on',...
    'LegendString',{'Water level anomailes' 'Precipitation' 'River discharge' 'Florida current'});
set(gca,'XLim',[min(RDD(:,1)) max(RDD(:,1))],'XTick',[min(RDD(:,1)):(max(RDD(:,1))-min(RDD(:,1)))/11:max(RDD(:,1))])
datetick('x','mmmdd','keepticks')
% xtickangle(45)
set(gcf,'color','w');


%Change the axis colors to match the requested line colors
for i=1:length(h3i.ax)
	set(h3i.ax(i),'ycolor',linecolors{i});	
end


saveas(fh,sprintf('/Users/kpark350/Ga_tech/Paper/DCF/OSM/Comp_GA_D.png'));



%% COMP MET


fh=figure('units','normalized','position',[0 0.3 1 .5]);

linecolors={'r' [0 .5 0] 'b'};
h3i=plotNy(WL_GA_M(:,1),WL_GA_M(:,4),1,...
    GA_M(:,1),GA_M(:,2),2,...
    GA_M(:,1),-(GA_M(:,4)-1013)./(1025*9.8)*100,3,...
    'Linewidth',2,...
    'YAxisLabels',{'[m]' '[m/s]' '[m]'},...
    'LineColor',linecolors,...
    'Ylim',[-0.2 2.5; 0 30; -0.2 2.5],...
    'FontSize',22,...
    'Fontname','TimesNewRoman',...
    'Parent',fh,... 
    'Grid','on',...
    'LegendString',{'Water level anomailes' 'Wind speed' 'Inverted barometer'});
set(gca,'XLim',[min(RDM(:,1)) max(RDM(:,1))],'XTick',[min(RDM(:,1)):(max(RDM(:,1))-min(RDM(:,1)))/11:max(RDM(:,1))])
datetick('x','mmmdd','keepticks')
% xtickangle(45)
set(gcf,'color','w');


%Change the axis colors to match the requested line colors
for i=1:length(h3i.ax)
	set(h3i.ax(i),'ycolor',linecolors{i});	
end


saveas(fh,sprintf('/Users/kpark350/Ga_tech/Paper/DCF/OSM/Comp_MET_GA_M.png'));



fh=figure('units','normalized','position',[0 0.3 1 .5]);

linecolors={'r' [0 .5 0] 'b'};
h3i=plotNy(WL_GA_D(:,1),WL_GA_D(:,4),1,...
    GA_D(:,1),GA_D(:,2),2,...
    GA_D(:,1),-(GA_D(:,4)-1013)./(1025*9.8)*100,3,...
    'Linewidth',2,...
    'YAxisLabels',{'[m]' '[m/s]' '[m]'},...
    'LineColor',linecolors,...
    'Ylim',[-0.2 2.5; 0 30; -0.2 2.5],...
    'FontSize',22,...
    'Fontname','TimesNewRoman',...
    'Parent',fh,... 
    'Grid','on',...
    'LegendString',{'Water level anomailes' 'Wind speed' 'Inverted barometer'});
set(gca,'XLim',[min(RDD(:,1)) max(RDD(:,1))],'XTick',[min(RDD(:,1)):(max(RDD(:,1))-min(RDD(:,1)))/11:max(RDD(:,1))])
datetick('x','mmmdd','keepticks')
% xtickangle(45)
set(gcf,'color','w');


%Change the axis colors to match the requested line colors
for i=1:length(h3i.ax)
	set(h3i.ax(i),'ycolor',linecolors{i});	
end


saveas(fh,sprintf('/Users/kpark350/Ga_tech/Paper/DCF/OSM/Comp_MET_GA_D.png'));


